name: Repo Dispatch Scheduler
on:
    schedule:
        # https://crontab.guru/every-hour
        - cron: 0 0 * * *
    # trigger workflow manually for testing
    workflow_dispatch: {}

jobs:
    update:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v2.4.0
            - name: install dependencies
              run: npm ci
            - name: compile
              run: npm run build
            - name: run repo_dispatch notifier
              env: 
                APP_ID: ${{ secrets.APP_ID }}
                CLIENT_ID: ${{ secrets.CLIENT_ID }}
                PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
              run: node lib/scripts/notify.js
